import '../styles/Reports.css';
import React from "react";

function Reports() {
  return (
    <div className="reports-container">
      <div className="reports-header">
        <div className="reports-header-row">
          <div className="search-container">
            <div className="search-icon">
              <span className="material-symbols-outlined">search</span>
            </div>
            <input
              className="search-input"
              placeholder="Search reports by type or date..."
            />
          </div>
          
          <div className="action-buttons">
            <button className="action-button filter">
              <span className="material-symbols-outlined">filter_list</span>
              <span>Date Range</span>
            </button>
            <button className="action-button primary">
              <span className="material-symbols-outlined">add</span>
              <span>Generate Report</span>
            </button>
          </div>
        </div>
      </div>

      <div className="reports-table">
        <div className="table-wrapper">
          <table>
            <thead>
              <tr>
                <th>Report Type</th>
                <th>Period</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Status</th>
                <th><span className="sr-only">Actions</span></th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="name">Monthly SOS Summary</td>
                <td>November 2024</td>
                <td>Admin User</td>
                <td>Nov 30, 2024</td>
                <td className="status">
                  <span className="status-badge completed">Complete</span>
                </td>
                <td className="actions">
                  <a href="#" className="action-link">Download</a>
                  <button className="deactivate-button">Share</button>
                </td>
              </tr>
              <tr>
                <td className="name">Doctor Performance</td>
                <td>Q4 2024</td>
                <td>System Admin</td>
                <td>Nov 28, 2024</td>
                <td className="status">
                  <span className="status-badge completed">Complete</span>
                </td>
                <td className="actions">
                  <a href="#" className="action-link">Download</a>
                  <button className="deactivate-button">Share</button>
                </td>
              </tr>
              <tr>
                <td className="name">Response Time Analysis</td>
                <td>Last 30 Days</td>
                <td>Medical Director</td>
                <td>Nov 25, 2024</td>
                <td className="status">
                  <span className="status-badge active">Processing</span>
                </td>
                <td className="actions">
                  <a href="#" className="action-link">View Progress</a>
                  <button className="deactivate-button">Cancel</button>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
        
        <div className="table-footer">
          <p>Showing 1 to 3 of 47 reports</p>
          <div className="pagination">
            <button className="pagination-button" disabled>Previous</button>
            <button className="pagination-button">Next</button>
          </div>
        </div>
      </div>
    </div>
  );
}

export default Reports;